### SEND USER DATA
POST http://localhost:3001/user-form HTTP/1.1
Content-Type: application/json

{
 "name": "sample",
 "dob" : "10 jan 2002",
 "email" : "fswics63217@c3hotunai.com",
 "phoneNo" : "+1 11192212"
}


### GET LIST OF USER DATA
GET http://localhost:3001/user-form?pageNo=1&per_page=2 HTTP/1.1
Content-Type: application/json

{
 "name": "sample",
 "dob" : "10 jan 2002",
 "email" : "kis2tah1137@brandoza.com",
 "phoneNo" : "+1 4211111111"
} 


### GET TOTAL USER FORM ENTRIES
GET http://localhost:3001/total-user-entries HTTP/1.1
