### SEND USER DATA
POST https://ill-erin-millipede-tam.cyclic.app/user-form HTTP/1.1
Content-Type: application/json

{
 "name": "sample",
 "dob" : "10 jan 2002",
 "email" : "kisotah137@brandoza.com",
 "phoneNo" : "+1 1111111111"
}